import express from 'express';
import path from 'path';
import cookieParser from 'cookie-parser';
import logger from 'morgan';
// import  cors from 'cors';
import indexRouter from './routes/index';
import logRouter from './routes/log';
import userRouter from './routes/users';
import postRouter from './routes/question';
import adminRouter from './routes/user-admin';
import reportRouter from './routes/report';
import authRouter from './routes/auth';
var app = express();

// app.use(cors());
app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, '../public')));
app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Methods", "GET,HEAD,OPTIONS,POST,PUT");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept, Authorization");
  next();
});
app.use('/', indexRouter);
app.use('/log', logRouter);
app.use('/user', userRouter);
app.use('/question', postRouter);
app.use('/admin', adminRouter);
app.use('/report', reportRouter);
app.use('/auth', authRouter);
export default app;
